import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  header: {
    alignItems: 'center',
    marginTop: 40,
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
  },
  subtitle: {
    fontSize: 16,
    marginTop: 5,
  },
  calendar: {
    marginTop: 20,
    paddingHorizontal: 10,
  },
  dayContainer: {
    alignItems: 'center',
    marginHorizontal: 10,
  },
  dayText: {
    fontWeight: 'bold',
    marginBottom: 0,
  },
  dateCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#ddd',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dateText: {
    fontWeight: 'bold',
  },
  taskSection: {
    marginTop: 0,
    paddingHorizontal: 20,
    paddingTop: 0,
    height: 480,
  },
  sectionTitle: {
    fontWeight: 'bold',
    fontSize: 18,
    marginBottom: 10,
    marginTop: 0,
  },
  taskContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderWidth: 2,
    borderRadius: 4,
    marginRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  taskText: {
    //backgroundColor: '#ededed',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 4,
    flex: 1,
    fontSize: 18,
  },
  fab: {
    position: 'absolute',
    bottom: 70,
    left: 30,
    backgroundColor: '#eb4731',
    borderRadius: 30,
    padding: 15,
    elevation: 5,
  },
  bottomBar: {
    height: 50,
    backgroundColor: '#ddd',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  dot: {
    width: 10,
    height: 10,
    backgroundColor: '#aaa',
    borderRadius: 5,
  },

  container: {
    flex: 1,
    top: 12,
    marginLeft: 12,
    marginRight: 16,
    backgroundColor: 'white',
  },
  content: {
    flex: 1,
    paddingTop: 80,
    paddingHorizontal: 30,
  },

  inlineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 0,
    flexWrap: 'wrap',
  },
  input: {
    backgroundColor: '#efefef',
    paddingHorizontal: 8,
    paddingVertical: 10,
    borderRadius: 4,
    marginHorizontal: 5,
    minWidth: 30,
    textAlignVertical: 'center',
    textAlign: 'left',
  },
  fixedButton: {
    position: 'absolute',
    bottom: 100,
    left: '10%',
    right: '10%',
    backgroundColor: '#eb4731',
    paddingVertical: 15,
    borderRadius: 8,
    alignItems: 'center',
  },
  buttonText: {
    fontWeight: 'bold',
    color: '#ffffff',
    fontSize: 16,
  },
  dropdown: {
    position: 'absolute',
    top: 45,
    left: 0,
    width: 100,
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    zIndex: 10,
    alignSelf: 'flex-start',
    overflow: 'hidden',
  },
  dropdownItem: {
    paddingVertical: 12,
    paddingHorizontal: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    backgroundColor: 'white',
  },
  dropdownItemText: {
    fontSize: 18,
    color: 'black',
    textAlign: 'center',
  },
});
