import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  header: {
    alignItems: 'center',
    marginTop: 40,
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    fontFamily: 'FjallaOne', 
  },
  subtitle: {
    fontSize: 16,
    marginTop: 5,
  },
  calendar: {
    marginTop: 20,
    paddingHorizontal: 10,
  },
  calendarContent: {
    paddingHorizontal: '25%',
  },
  dayContainer: {
    alignItems: 'center',
    marginHorizontal: 10,
    width: 40,
    height: 72,
    justifyContent: 'center',
  },
  currentDayContainer: {
    backgroundColor: '#f0f0f0',
    padding: 8,
    borderRadius: 12,
    height: 72,
  },
  selectedDayContainer: {
    backgroundColor: '#fff0f0',
    padding: 8,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#eb4731',
    height: 72,
  },
  dayText: {
    fontWeight: 'bold',
    marginBottom: 8,
  },
  currentDayText: {
    color: '#eb4731',
  },
  selectedDayText: {
    color: '#eb4731',
    fontWeight: 'bold',
  },
  dateCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#ddd',
    justifyContent: 'center',
    alignItems: 'center',
  },
  currentDateCircle: {
    backgroundColor: '#eb4731',
  },
  selectedDateCircle: {
    backgroundColor: '#eb4731',
    borderWidth: 2,
    borderColor: '#fff',
  },
  dateText: {
    fontWeight: 'bold',
  },
  currentDateText: {
    color: 'white',
  },
  selectedDateText: {
    color: 'white',
    fontWeight: 'bold',
  },
  noTasksText: {
    textAlign: 'center',
    color: '#666',
    fontSize: 16,
    marginTop: 20,
  },
  taskSectionContainer: {
    position: 'absolute',
    top: 220,
    left: 0,
    right: 0,
    bottom: 40,
  },
  taskSection: {
    paddingHorizontal: 20,
    paddingTop: 0,
  },
  sectionTitle: {
    fontWeight: 'bold',
    fontSize: 18,
    marginBottom: 10,
    marginTop: 0,
  },
  taskContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderWidth: 2,
    borderRadius: 4,
    marginRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  taskText: {
    fontSize: 18,
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 12,
  },
  deadlineText: {
    fontSize: 14,
    color: '#666',
    marginLeft:32,
    marginTop: -4,
    paddingHorizontal: 12,
  },
  dueDateText: {
    fontSize: 16,
    color: '#666',
    paddingHorizontal: 10,
    paddingBottom: 8,
  },
  fab: {
    position: 'absolute',
    bottom: 70,
    left: 30,
    backgroundColor: '#eb4731',
    borderRadius: 30,
    padding: 15,
    elevation: 5,
  },
  bottomBar: {
    height: 50,
    backgroundColor: '#ddd',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  dot: {
    width: 10,
    height: 10,
    backgroundColor: '#aaa',
    borderRadius: 5,
  },

  container: {
    flex: 1,
    top: 12,
    marginLeft: 12,
    marginRight: 16,
    backgroundColor: 'white',
  },
  content: {
    flex: 1,
    paddingTop: 80,
    paddingHorizontal: 30,
  },

  inlineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 0,
    flexWrap: 'wrap',
  },
  input: {
    borderWidth: 2,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 8,
    minWidth: 100,
    textAlign: 'left',
    fontSize: 16,
  },
  fixedButton: {
    position: 'absolute',
    bottom: 100,
    left: '10%',
    right: '10%',
    backgroundColor: '#eb4731',
    paddingVertical: 15,
    borderRadius: 8,
    alignItems: 'center',
  },
  buttonText: {
    fontWeight: 'bold',
    color: '#ffffff',
    fontSize: 16,
  },
  dropdown: {
    position: 'absolute',
    top: 45,
    left: 0,
    width: 100,
    backgroundColor: 'white',
    borderWidth: 2,
    borderColor: '#ccc',
    borderRadius: 8,
    zIndex: 10,
    alignSelf: 'flex-start',
    overflow: 'hidden',
  },
  dropdownItem: {
    paddingVertical: 12,
    paddingHorizontal: 10,
    justifyContent: 'left',
    alignItems: 'left',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    backgroundColor: 'white',
  },
  dropdownItemText: {
    fontSize: 18,
    color: 'black',
    textAlign: 'left',
  },
  dateTimeContainer: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'left',
    justifyContent: 'left',
  },
  dateButton: {
    borderWidth: 2,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 8,
    minWidth: 100,
    alignItems: 'center',
  },
  timeButton: {
    borderWidth: 2,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 8,
    minWidth: 100,
    alignItems: 'center',
  },
  dateButtonText: {
    textAlign: 'center',
    fontSize: 16,
  },
  timeButtonText: {
    textAlign: 'center',
    fontSize: 16,
  },
});
